1. Write a function to compute 5/0 and use try/except to catch the exceptions.
    

In [19]:
def test():
    return 5/0

try:
    test()
except ZeroDivisionError:
    print("Cannot be divided by Zero")


Cannot be divided by Zero


2. Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [20]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

list_play = [(x+" "+y+" "+z) for x in subjects for y in verbs for z in objects]
for s in list_play:
    print(s)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


3.Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [21]:
import numpy as np

def Vandermode(input, n , increase):
    if increase:
        output = np.array([x**i for x in input for i in range(n)]).reshape(input.size,n)
    else:
        output = np.array([x**(n-i-1) for x in input for i in range(n)]).reshape(input.size,n)
    return output

input_val = np.array([1,2,3,4,5])
col = 5
dec_order = Vandermode(input_val,col,True)
asc_order = Vandermode(input_val,col,False)

print("The input array is:",input_val,"\n")
print("Number of columns in output matrix should be:",col,"\n")
print("Matrix with Increasing power:\n\n",dec_order,"\n")
print("Matrix with Decreasing power:\n\n",asc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Matrix with Increasing power:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

Matrix with Decreasing power:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

