In [18]:
import numpy as np
   
def Vandermonde_matrix(input, n, increase):
    if increase:
        output = np.array([x**i for x in input for i in range(n)]).reshape(input.size,n)
    else:
        output = np.array([x**(n-i-1) for x in input for i in range(n)]).reshape(input.size,n)    
    return output

input_val = np.array([1,2,3,4,5])
col = 5
dec_order = Vandermonde_matrix(input_val,col,True)
asc_order = Vandermonde_matrix(input_val,col,False)

print("The input array is:",input_val,"\n")
print("Number of columns in output matrix should be:",col,"\n")
print("Matrix with Increasing power:\n\n",dec_order,"\n")
print("Matrix with Decreasing power:\n\n",asc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Matrix with Increasing power:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

Matrix with Decreasing power:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 



In [19]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3

def moving_average(a,n):
    temp = np.cumsum(a)
    temp[n:] = temp[n:] - temp[:-n]
    return (temp[n - 1:] / n)

moving_average(input,n)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])