# Assignment

In [124]:
import numpy as np

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [125]:
a = 6*np.ones((5,5))
print("Original Array \n")
print(a)
print("\n")
print("6 on the border and 0 inside in the array \n")
a[1:-1,1:-1] = 0
print(a)

Original Array 

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


6 on the border and 0 inside in the array 

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [126]:
z = 3*np.ones((8,8))
print(z)
print("\n")
z[1::2,::2] = 9
z[::2,1::2]= 9
print("Checkerboard pattern")
print(z)

[[3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]]


Checkerboard pattern
[[3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [127]:
a = np.empty((3,4))
print(a)
b = np.full((3,3,),6)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [128]:
i = [0, 12, 45.21 ,34, 99.91]
x = np.array(i)
print("\n Values in Fahrenheit degrees \n")
print(x)
y = (5*x/9 - 5*32/9)
print("\n Values in Centigrade degrees \n")
print(y)


 Values in Fahrenheit degrees 

[ 0.   12.   45.21 34.   99.91]

 Values in Centigrade degrees 

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [129]:
a = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print("Real part of the array")
print(a.real)
print("\nImaginary part of the array")
print(a.imag)


Real part of the array
[1.         0.70710678]

Imaginary part of the array
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [130]:
a = np.array([0,10,20,40,60])
print(a)
b = np.array([0, 40])
print(b)
print("Compare each element of array1 and array2")
print(np.in1d(a,b))

[ 0 10 20 40 60]
[ 0 40]
Compare each element of array1 and array2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [131]:
x = np.array([0,10,20,40,60])
print(x)
y = np.array([10,30,40])
print(y)
print("Common values between two arrays")
print(np.intersect1d(x,y))

[ 0 10 20 40 60]
[10 30 40]
Common values between two arrays
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [132]:

a = np.array([10,10,20,20,30,30])
b = np.unique(a)
print("Original array")
print(a)
print("Unique elements of above array")
print(b)
print("----------------------")

x = np.array([[1,1],[2,3]])
print("Original array")
print(x)
print("Unique elements of above array")
y = np.unique(x)
print(y)

Original array
[10 10 20 20 30 30]
Unique elements of above array
[10 20 30]
----------------------
Original array
[[1 1]
 [2 3]]
Unique elements of above array
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [133]:
a = np.array([0,10,20,40,60,80])
print(a)
b = np.array([10,30,40,50,70])
print(b)
print("\nUnique values that are in only one (not both) of the input arrays")
print(np.setxor1d(a, b))

[ 0 10 20 40 60 80]
[10 30 40 50 70]

Unique values that are in only one (not both) of the input arrays
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [134]:
print(np.all([[1,1]]))
print(np.all([[1,0]]))
print(np.all([[0,1]]))
print(np.all([[0,0]]))

True
False
False
False


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [135]:
print(np.any([[1,1]]))
print(np.any([[1,0]]))
print(np.any([[0,1]]))
print(np.any([[0,0]]))

True
True
True
False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [136]:
a = [1,2,3,4]
print("Original array")
print(a)
b = np.tile(a,2)
c = np.tile(a,3)
print("Repeating 2 times\n",b)
print("Repeating 3 times\n",c)


Original array
[1, 2, 3, 4]
Repeating 2 times
 [1 2 3 4 1 2 3 4]
Repeating 3 times
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [137]:
a = [1,2,3,4,5,6]
print("Original Array:",a)
print("Maximum Values:",np.argmax(a))
print("Minimum Values:",np.argmin(a))

Original Array: [1, 2, 3, 4, 5, 6]
Maximum Values: 5
Minimum Values: 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [138]:
a = np.array([1,2])
b = np.array([4,5])
print("Array a:",a)
print("Array b:",b)
w= np.greater(a,b)
x = np.greater_equal(a,b)
y = np.less(a,b)
z = np.less_equal(a,b)
print("a > b\n",w)
print("a >= b\n",x)
print("a < b\n",y)
print("a <= b\n",z)

Array a: [1 2]
Array b: [4 5]
a > b
 [False False]
a >= b
 [False False]
a < b
 [ True  True]
a <= b
 [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [139]:
a = np.array([[4,6],[2,1]])
print("Original array:")
print(a)
b = np.sort(a, axis =0)
print("Sort along the first axis\n",b)
print("Sort along the last axis")
print(np.sort(b, axis =1))

Original array:
[[4 6]
 [2 1]]
Sort along the first axis
 [[2 1]
 [4 6]]
Sort along the last axis
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [140]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names,last_names))
print(x)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [141]:
a = np.array([[ 0,10,20], [20,30,40]])
print("Original array\n",a)
print("Values bigger than 10 =", a[a > 10])
print("Their indices are", np.nonzero(a > 10))


Original array
 [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [142]:
z = np.empty((4,4))
print("%d bytes" %(z.size * z.itemsize))


128 bytes


## Great Job!